### ISSUE TITLE
Current status?

### ISSUE THREAD

**Issue by BjarkeMeier** [aroch/protobuf-dataframe#4]
Hi,

I've been looking for ProtoBuf support in PySpark. This repo is the only thing I've found. Since the last contribution is 2 years ago I'd like to know what is your perspective on this project? And do you happen to know about any planned built-in ProtoBuf support in PySpark?

I've started using the project and created my first tiny pull request (#3). So far it works great for my needs. So thank you very much for this great solution. I have btw. yet another upcoming pull request regarding an enum bug fix regarding enums where indexes are not consecutive numbers and am considering adding a few unit tests in case the project is active and accepts pull requests.

**Comment by aroch** [comment]
Hi @BjarkeMeier,

I'm glad you find this project useful for your needs!
Actually, the last contribution was done 24 days ago by a PR created by @eldandev 😄 .

Personally, I no longer maintain this repo but would be happy to accept PRs.

**Comment by aroch** [comment]
Regarding the PySpark support. Honestly, I did not check developments in the area recently.

**Comment by BjarkeMeier** [comment]
Hi @aroch, thank you for answering. And also thank you for accepting my first PR :-)
